from . import views
from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('user/token/', views.MyTokenObtainPairView.as_view()),
    path('user/token/refresh', TokenRefreshView.as_view()),
    path('user/register', views.RegisterView.as_view()),
    path('user/password-reset/<email>/', views.PasswordResetEmailVerifyView.as_view()),
    path("user/password-change/", views.PasswordChangeView.as_view()),
    path("user/profile/<user_id>/", views.ProfileView.as_view()),
    path("user/change-password/", views.ChangePasswordView.as_view()),

    path("course/category/", views.CategoryListView.as_view()),
    path("course/course-list/", views.CourseListView.as_view()),
    path("course/search/", views.SearchCourseView.as_view()),
    path("course/course-detail/<course_id>/", views.CourseDetailView.as_view()),
    path("course/cart/", views.CartView.as_view()),
    path("course/cart-list/<cart_id>/", views.CartListView.as_view()),
    path("cart/stats/<cart_id>/", views.CartStatsView.as_view()),
    path("course/cart-item-delete/<cart_id>/<item_id>/", views.CartItemDeleteView.as_view()),
    path("order/create-order/", views.CreateOrderView.as_view()),
    path("order/checkout/<oid>/", views.CheckoutView.as_view()),
    path("order/coupon/", views.CouponApplyView.as_view()),
    path("payment/stripe-checkout/<order_oid>/", views.StripeCheckoutView.as_view()),
    path("payment/payment-sucess/", views.PaymentSuccessView.as_view()),

    path("student/summary/<user_id>/", views.StudentSummaryView.as_view()),
    path("student/course-list/<user_id>/", views.StudentCourseListView.as_view()),
    path("student/course-detail/<user_id>/<enrollment_id>/", views.StudentCourseDetailView.as_view()),
    path("student/course-completed/", views.StudentCourseCompletedCreateView.as_view()),
    path("student/course-note/<user_id>/<enrollment_id>/", views.StudentNoteCreateView.as_view()),
    path("student/course-note-detail/<user_id>/<enrollment_id>/<note_id>/", views.StudentNoteDetailView.as_view()),
    path("student/rate-course/", views.StudentRateCourseCreateView.as_view()),
    path("student/review-detail/<user_id>/<review_id>/", views.StudentRateCourseUpdateView.as_view()),
    path("student/wishlist/<user_id>/", views.StudentWishListListCreateView.as_view()),
    path("student/question-answer-list-create/<course_id>/", views.QuestionAnswerListCreateView.as_view()),
    path("student/question-answer-message-create/", views.QuestionAnswerMessageSendView.as_view()),
    path('student/course-progress/<int:user_id>/', views.student_course_progress, name='student-course-progress'),

    path("teacher/summary/<teacher_id>/", views.TeacherSummaryView.as_view()),
    path("teacher/course-lists/<teacher_id>/", views.TeacherCourseListView.as_view()),
    path("teacher/review-lists/<teacher_id>/", views.TeacherReviewListView.as_view()),
    path("teacher/review-detail/<teacher_id>/<review_id>/", views.TeacherReviewDetailView.as_view()),
    path("teacher/student-lists/<teacher_id>/", views.TeacherStudentsListVIew.as_view({'get': 'list'})),
    path("teacher/all-months-earning/<teacher_id>/", views.TeacherAllMonthEarningView),
    path("teacher/best-course-earning/<teacher_id>/", views.TeacherBestSellingCourseView.as_view({'get': 'list'})),
    path("teacher/course-order-list/<teacher_id>/", views.TeacherCourseOrdersListView.as_view()),
    path("teacher/question-answer-list/<teacher_id>/", views.TeacherQuestionAnswerListView.as_view()),
    path("teacher/coupon-list/<teacher_id>/", views.TeacherCouponListCreateView.as_view()),
    path("teacher/coupon-detail/<teacher_id>/<coupon_id>/", views.TeacherCouponDetailView.as_view()),
    path("teacher/noti-list/<teacher_id>/", views.TeacherNotificationListView.as_view()),
    path("teacher/noti-detail/<teacher_id>/<noti_id>", views.TeacherNotificationDetailView.as_view()),
    path("teacher/course-create/", views.CourseCreateView.as_view()),
    path("teacher/course-update/<teacher_id>/<course_id>/", views.CourseUpdateView.as_view()),
    path("teacher/course-detail/<course_id>/", views.CourseDetailView.as_view()),
    path("teacher/course/variant-delete/<variant_id>/<teacher_id>/<course_id>/", views.CourseVariantDeleteView.as_view()),
    path("teacher/course/variant-item-delete/<variant_id>/<variant_item_id>/<teacher_id>/<course_id>/", views.CourseVariantItemDeleteVIew.as_view()),
    path('teacher/enrollment-trends/<int:teacher_id>/', views.enrollment_trends, name='enrollment-trends'),
    path('teacher/all-months-earning/<int:teacher_id>/', views.TeacherAllMonthEarningView, name='all-months-earning'),
    path('teacher/revenue-distribution/<int:teacher_id>/', views.revenue_distribution, name='revenue-distribution'),
    path('teacher/course-popularity-vs-revenue/<int:teacher_id>/', views.course_popularity_vs_revenue, name='course-popularity-vs-revenue'),

    path("teacher/create-quiz/", views.QuizCreateView.as_view(), name='quiz-create'),
    path("teacher/quizzes/", views.QuizListView.as_view(), name='quiz-list'),
    path("teacher/quiz-detail/<int:pk>/", views.QuizDetailView.as_view(), name='quiz-detail'),
    path('teacher/edit-quiz/<int:pk>/', views.QuizEditView.as_view(), name='edit-quiz'),
    path('teacher/publish-quiz/<int:pk>/', views.QuizDetailView.as_view(), name='publish-quiz'),
    
    path("student/quizzes/<int:course_id>/", views.StudentQuizListView.as_view(), name='student-quiz-list'),
    path("student/quiz-detail/<int:quiz_id>/", views.StudentQuizDetailView.as_view(), name='student-quiz-detail'),
    path("student/submit-quiz/<int:student_id>/", views.SubmitQuizView.as_view(), name='submit-quiz'),
    path('student/quiz-scores/<int:user_id>/', views.StudentQuizScoresView.as_view(), name='student-quiz-scores'),
    
     # Custom Admin URLs
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
]