services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: app:django
    container_name: django_container
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      DB_NAME: devbook
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - django_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_container
    volumes:
      - ./frontend:/app
    ports:
      - "8000:8000"
    networks:
      - django_network

  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
